# Generated by Django 3.2.4 on 2021-06-25 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_porche'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Porche',
            new_name='Porsche',
        ),
    ]
