# Generated by Django 3.2.4 on 2021-06-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('body', models.TextField(null=True)),
            ],
        ),
    ]
