# Generated by Django 3.2.4 on 2021-07-12 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
