# Generated by Django 3.2.4 on 2021-06-22 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_dog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='name',
            new_name='title',
        ),
    ]
