# Generated by Django 3.2.4 on 2021-06-22 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_name_dog_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='title',
            new_name='name',
        ),
    ]
